#! /usr/bin/env python
# -*- coding: utf-8 -*-
from snakemake.utils import min_version
import os
import pandas as pd

min_version("6.4.1")

configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/download_bam.smk"
include: "rules/make_ubam.smk"
# include: "rules/align_star.smk"
# include: "rules/telescope.smk"
# include: "rules/stringtie.smk"

localrules: download_convert
rule download_covert:
    input:
        "resources/sample_table.tsv"
    output:
        "results/ubam/{sample_id}.bam"

localrules: sample_complete
rule sample_complete:
    input:
        "results/align_multi/{sample_id}/Aligned.out.cram",
        rules.telescope.output,
        rules.stringtie.output
    output:
        touch("results/complete/{sample_id}.txt")

localrules: all
rule all:
    input:
        expand("results/complete/{s}.txt", s=list(samples.index))

localrules: msk
rule msk:
    input:
        expand("results/complete/{s}.txt", s=list(samples.index))
