samples: "/Users/phoebefei/Library/CloudStorage/OneDrive-med.cornell.edu/WCM/Metastatic UM Prj/Cutaneous Bulk/gdc_sample_sheet.2022-09-13.tsv"
#access token to be used in  -t tokenfile.txt
tokens: "/Users/phoebefei/Library/CloudStorage/OneDrive-med.cornell.edu/WCM/Metastatic UM Prj/Cutaneous Bulk/PHOFEI.txt"
star_align_multi:
    genomeDir: "resources/STAR_gdc38_gencode38"
    outFilterMultimapNmax: 200
    winAnchorMultimapNmax: 200
telescope:
    annotation: "resources/retro.hg38.v1.gtf"
genome_fasta: "resources/GRCh38.d1.vd1.fa"
annotation_gtf: "resources/gencode.v38.annotation.gtf"

